name: Deploy DEV (manual)

on:
  workflow_dispatch:
    
jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Block main
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "Deploy DEV n√£o pode usar a branch main."
            exit 1
          fi

      - name: Checkout selected branch
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Validate + Deploy bundle (dev)
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
        run: |
          databricks bundle validate -t dev
          databricks bundle deploy -t dev
